project:
  type: website
  output-dir: docs

website:
  title: "Aliza Mithwani"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sketch
    css: styles.css
    toc: true

editor: visual

